lib/bloomchain_web/router.ex
defmodule BloomchainWeb.Router do
  use BloomchainWeb, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug :fetch_session
    plug(:fetch_flash)
    # plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :customer do
    plug(BloomchainWeb.Plug.Redirect)
    plug(BloomchainWeb.Plug.SetSectionData)
  end

  pipeline :admin do
    plug(BloomchainWeb.Plug.Authentication)
    plug(BloomchainWeb.Plug.EnsureAuthentication)
    plug(:put_layout, {BloomchainWeb.LayoutView, :admin})
  end

  pipeline :sign_in do
    plug(:put_layout, {BloomchainWeb.LayoutView, :sign_in})
  end

  pipeline :api do
    plug(:accepts, ["json", "multipart/form-data"])
  end

  pipeline :xml do
    plug(:accepts, ["xml"])
    plug(:put_layout, false)
  end

  scope "/admin", BloomchainWeb, as: :admin do
    pipe_through([:browser, :admin])

    get("/", Admin.HomeController, :index)

    scope "/api/v1" do
      pipe_through [:api]

      get("/articles/search", Admin.Api.V1.ArticleController, :search)
      resources("/articles", Admin.Api.V1.ArticleController)

      get "/users/current", Admin.Api.V1.UserController, :current
      resources("/users", Admin.Api.V1.UserController)

      resources("/tags", Admin.Api.V1.TagController)
      resources("/media", Admin.Api.V1.MediaController)
      resources("/subscribers", Admin.Api.V1.SubscriberController, only: [:index])
      resources("/archives", Admin.Api.V1.ArchiveController)
      resources("/authors", Admin.Api.V1.AuthorController)
      resources("/sections", Admin.Api.V1.SectionController)
      resources("/redirects", Admin.Api.V1.RedirectController)
      resources("/banners", Admin.Api.V1.BannerController)
      resources("/statistics", Admin.Api.V1.StatisticController, only: [:index])
    end

    scope "/preview" do
      pipe_through [:customer]

      get "/articles/:type/:slug", Admin.Preview.ArticleController, :show
    end

    get("/*path", Admin.HomeController, :index)
  end

  scope "/session", BloomchainWeb do
    pipe_through([:browser, :sign_in])

    delete("/", SessionController, :delete)
    resources("/", SessionController, only: [:create, :new])
  end

  get("/sitemap.xml", BloomchainWeb.SitemapController, :index)

  scope "/sitemap", BloomchainWeb do
    pipe_through([:xml])

    resources("/", SitemapController, only: [:show], param: "property")
  end

  scope "/api", BloomchainWeb do
    pipe_through [:api]

    resources("/index", Api.IndexController, only: [:index])
    resources("/subscription", Api.SubscriptionController, only: [:create])
    resources("/events", Api.EventController, only: [:create])
  end

  scope "/", BloomchainWeb do
    pipe_through([:xml])

    get("/feed", FeedController, :index)
    get("/:type/feed", FeedController, :show)
  end

  scope "/", BloomchainWeb do
    pipe_through([:browser, :customer])

    get("/", PageController, :index)

    get("/search", SearchController, :index)
    get("/tag/:slug", TagController, :show)

    get("/:type/:slug", ArticleController, :show)
    get("/:type", SectionController, :index)
  end
end

lib/bloomchain_web/templates/page/_analysis.html.eex
<div class="col-lg-6">
    <h1 class="bc-article__z-index highlight mb-4"><%= @conn.assigns.sections["analysis"].name %><%= link("Больше", to: section_path(@conn, :index, "analysis"), class: "btn btn-title") %></h1>

    <%= SharedView.main_article_tag(List.first(@articles), conn: @conn) %>

    <%= for article <- @articles |> tl() do %>
      <hr class="bc-article__separator mx-0 my-3">
      <%= render_article(article, conn: @conn,  path: article_path(@conn, :show, "analysis", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/_calendar.html.eex
<div class="col-lg-6 mt-lg-0 mt-5">
    <h1 class="bc-article__z-index highlight mb-4"><%= @conn.assigns.sections["calendar"].name %><%= link("Больше", to: section_path(@conn, :index, "calendar"), class: "btn btn-title") %></h1>

    <%= SharedView.main_article_tag(List.first(@articles), conn: @conn) %>

    <%= for article <- @articles |> tl() do %>
      <hr class="bc-article__separator mx-0 my-3">
      <%= render_article(article, conn: @conn,  path: article_path(@conn, :show, "calendar", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/_detailed.html.eex
<div class="col-lg-6 mt-lg-0 mt-5">
    <h1 class="highlight mb-4"><%= @conn.assigns.sections["detailed"].name %><%= link("Больше", to: section_path(@conn, :index, "detailed"), class: "btn btn-title") %></h1>

    <%= SharedView.main_article_tag(List.first(@articles), conn: @conn) %>

    <%= for article <- @articles |> tl() do %>
      <hr class="bc-article__separator mx-0 my-3">
      <%= render_article(article, conn: @conn, path: article_path(@conn, :show, "detailed", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/_in_russia.html.eex
<div class="col-lg-6">
    <h1 class="bc-article__z-index highlight mb-4"><%= @conn.assigns.sections["in-russia"].name %><%= link("Больше", to: section_path(@conn, :index, "in-russia"), class: "btn btn-title") %></h1>

    <%= SharedView.main_article_tag(List.first(@articles), conn: @conn) %>

    <%= for article <- @articles |> tl() do %>
      <hr class="bc-article__separator mx-0 my-3">
      <%= render_article(article, conn: @conn,  path: article_path(@conn, :show, "in-russia", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/_newsfeed.html.eex
<div class="bc-news col-lg-6">
    <h1 class="highlight"><%= @conn.assigns.sections["newsfeed"].name %><%= link("Больше", to: section_path(@conn, :index, "newsfeed"), class: "btn btn-title") %></h1>

    <%= for article <- @articles do %>
      <%= render_short(article, conn: @conn, path: article_path(@conn, :show, "newsfeed", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/_people.html.eex
<div class="col-lg-6 mt-lg-0 mt-5">
    <h1 class="bc-article__z-index highlight mb-4"><%= @conn.assigns.sections["people"].name %><%= link("Больше", to: section_path(@conn, :index, "people"), class: "btn btn-title") %></h1>

    <%= SharedView.main_article_tag(List.first(@articles), conn: @conn) %>

    <%= for article <- @articles |> tl() do %>
      <hr class="bc-article__separator mx-0 my-3">
      <%= render_article(article, conn: @conn,  path: article_path(@conn, :show, "people", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/_research.html.eex
<div class="col-lg-6">
    <h1 class="bc-article__z-index highlight mb-4"><%= @conn.assigns.sections["research"].name %><%= link("Больше", to: section_path(@conn, :index, "research"), class: "btn btn-title") %></h1>

    <%= SharedView.main_article_tag(List.first(@articles), conn: @conn) %>

    <%= for article <- @articles |> tl() do %>
      <hr class="bc-article__separator mx-0 my-3">
      <%= render_article(article, conn: @conn,  path: article_path(@conn, :show, "research", article.slug)) %>
    <% end %>
</div>

lib/bloomchain_web/templates/page/detailed.html.eex
<div class="container py-4">
  <div class="row">
    <div class="col-md-12 mt-md-0"><a class="bc-article__overlay-link" href="#">
        <div class="bc-article__image"><img src="assets/images/img-bitcoin.jpg">
          <p>Курс криптовалюты Ethereum превысил $400</p><span class="bc-article__image__published small">2 часа назад</span>
          <div class="d-flex align-items-center"><i class="mr-1 icon-user-white"></i><span class="small mr-sm-4 mr-3">Stanley Wade</span><i class="mr-1 icon-view-white"></i><span class="small mr-sm-4 mr-3">23</span><i class="mr-1 icon-clock-white"></i><span class="small">17 мин</span></div>
        </div></a>
      <div class="mt-4"></div><a class="bc-article__heading bc-article__heading__h2" href="http://">Криптобиржа Coincheck вернет средства своим клиентам после взлома</a>
      <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
      <hr class="bc-article__separator mx-0 my-3">
      <div class="row">
        <div class="col-xl-6"><a class="bc-article__heading" href="http://">Земан призвал Москву и Запад отказаться от санкций</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3"><a class="bc-article__heading" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3 d-xl-none">
        </div>
        <div class="col-xl-6"><a class="bc-article__heading" href="http://">Земан призвал Москву и Запад отказаться от санкций</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3"><a class="bc-article__heading" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/bloomchain_web/templates/page/in_russia.html.eex
<div class="container py-4">
  <div class="row">
    <div class="col-md-12 mt-md-0"><a class="bc-article__overlay-link" href="#">
        <div class="bc-article__image"><img src="assets/images/img-bitcoin.jpg">
          <p>Курс криптовалюты Ethereum превысил $400</p><span class="bc-article__image__published small">2 часа назад</span>
          <div class="d-flex align-items-center"><i class="mr-1 icon-user-white"></i><span class="small mr-sm-4 mr-3">Stanley Wade</span><i class="mr-1 icon-view-white"></i><span class="small mr-sm-4 mr-3">23</span><i class="mr-1 icon-clock-white"></i><span class="small">17 мин</span></div>
        </div></a>
      <div class="mt-4"></div><a class="bc-article__heading bc-article__heading__h2" href="http://">Криптобиржа Coincheck вернет средства своим клиентам после взлома</a>
      <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
      <hr class="bc-article__separator mx-0 my-3">
      <div class="row">
        <div class="col-xl-6"><a class="bc-article__heading" href="http://">Земан призвал Москву и Запад отказаться от санкций</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3"><a class="bc-article__heading" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3 d-xl-none">
        </div>
        <div class="col-xl-6"><a class="bc-article__heading" href="http://">Земан призвал Москву и Запад отказаться от санкций</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3"><a class="bc-article__heading" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/bloomchain_web/templates/page/index.html.eex
<div class="container py-4">
    <div class="row">
      <%= if length(@context[:newsfeed]) > 0 do %>
        <%= render "_newsfeed.html", conn: @conn, articles: @context[:newsfeed] %>
      <% end %>
      <%= if length(@context[:detailed]) > 0 do %>
        <%= render "_detailed.html", conn: @conn, articles: @context[:detailed] %>
      <% end %>
    </div>
</div>

<div class="bg-white">
    <div class="container py-4">
        <div class="row">
          <%= if length(@context[:analysis]) > 0 do %>
            <%= render "_analysis.html", conn: @conn, articles: @context[:analysis] %>
          <% end %>
          <%= if length(@context[:people]) > 0 do %>
            <%= render "_people.html", conn: @conn, articles: @context[:people] %>
          <% end %>
        </div>
    </div>
</div>

<div class="container py-4">
    <div class="row">
      <%= if length(@context[:research]) > 0 do %>
        <%= render "_research.html", conn: @conn, articles: @context[:research] %>
      <% end %>
      <%= if length(@context[:calendar]) > 0 do %>
        <%= render "_calendar.html", conn: @conn, articles: @context[:calendar] %>
      <% end %>
    </div>
</div>

lib/bloomchain_web/templates/page/newsfeed.html.eex
<div class="container pt-4 pb-5">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="highlight highlight-date"><span class="mr-1 d-inline-flex">Четверг</span><span class="d-inline-flex font-weight-semibold">14.05.2018</span></h1>
      <div class="bc-news mt-3">
        <div class="bc-news__item"><span class="bc-news__time">07:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Путин поговорил с Трампом по телефону</a></div>
        <div class="bc-news__item"><span class="bc-news__time">08:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Forbes назвал самых высокооплачиваемых моделей мира</a></div>
        <div class="bc-news__item"><span class="bc-news__time">09:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Кадырова наградили золотой медалью РАН за заслуги в онкологии</a></div>
        <div class="bc-news__item"><span class="bc-news__time">10:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Топилин рассказал об отношении работодателей к электронным трудовым книжкам</a></div>
        <div class="bc-news__item"><span class="bc-news__time">11:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Земан призвал Москву и Запад отказаться от взаимных санкций</a></div>
        <div class="bc-news__item"><span class="bc-news__time">12:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Доступ на Красную площадь 23 ноября закроют из-за учений ФСО</a></div>
        <div class="bc-news__item"><span class="bc-news__time">13:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
        <div class="bc-news__item"><span class="bc-news__time">14:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Путин поговорил с Трампом по телефону</a></div>
        <div class="bc-news__item"><span class="bc-news__time">15:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Forbes назвал самых высокооплачиваемых моделей мира</a></div>
        <div class="bc-news__item"><span class="bc-news__time">16:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Кадырова наградили золотой медалью РАН за заслуги в онкологии</a></div>
        <div class="bc-news__item"><span class="bc-news__time">17:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Топилин рассказал об отношении работодателей к электронным трудовым книжкам</a></div>
        <div class="bc-news__item"><span class="bc-news__time">18:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Земан призвал Москву и Запад отказаться от взаимных санкций</a></div>
        <div class="bc-news__item"><span class="bc-news__time">19:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Доступ на Красную площадь 23 ноября закроют из-за учений ФСО</a></div>
        <div class="bc-news__item"><span class="bc-news__time">20:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
        <div class="bc-news__item"><span class="bc-news__time">21:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
        <div class="bc-news__item"><span class="bc-news__time">22:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
        <div class="bc-news__item"><span class="bc-news__time">23:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
      </div>
    </div>
  </div>
</div>
<div class="bg-white">
  <div class="container py-4">
    <div class="row mt-3">
      <div class="col-lg-12">
        <h1 class="bc-article__z-index highlight highlight-date"><span class="mr-1 d-inline-flex">Среда</span><span class="d-inline-flex font-weight-semibold">13.05.2018</span></h1>
        <div class="bc-news mt-3">
          <div class="bc-news__item"><span class="bc-news__time">07:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Путин поговорил с Трампом по телефону</a></div>
          <div class="bc-news__item"><span class="bc-news__time">08:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Forbes назвал самых высокооплачиваемых моделей мира</a></div>
          <div class="bc-news__item"><span class="bc-news__time">09:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Кадырова наградили золотой медалью РАН за заслуги в онкологии</a></div>
          <div class="bc-news__item"><span class="bc-news__time">10:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Топилин рассказал об отношении работодателей к электронным трудовым книжкам</a></div>
          <div class="bc-news__item"><span class="bc-news__time">11:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Земан призвал Москву и Запад отказаться от взаимных санкций</a></div>
          <div class="bc-news__item"><span class="bc-news__time">12:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Доступ на Красную площадь 23 ноября закроют из-за учений ФСО</a></div>
          <div class="bc-news__item"><span class="bc-news__time">13:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
          <div class="bc-news__item"><span class="bc-news__time">14:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Путин поговорил с Трампом по телефону</a></div>
          <div class="bc-news__item"><span class="bc-news__time">15:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Forbes назвал самых высокооплачиваемых моделей мира</a></div>
          <div class="bc-news__item"><span class="bc-news__time">16:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Кадырова наградили золотой медалью РАН за заслуги в онкологии</a></div>
          <div class="bc-news__item"><span class="bc-news__time">17:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Топилин рассказал об отношении работодателей к электронным трудовым книжкам</a></div>
          <div class="bc-news__item"><span class="bc-news__time">18:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Земан призвал Москву и Запад отказаться от взаимных санкций</a></div>
          <div class="bc-news__item"><span class="bc-news__time">19:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">Доступ на Красную площадь 23 ноября закроют из-за учений ФСО</a></div>
          <div class="bc-news__item"><span class="bc-news__time">20:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
          <div class="bc-news__item"><span class="bc-news__time">21:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
          <div class="bc-news__item"><span class="bc-news__time">22:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
          <div class="bc-news__item"><span class="bc-news__time">23:30</span><a class="bc-news__title bc-article__heading font-weight-medium" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a></div>
        </div>
      </div>
      <div class="container pl-0">
        <button class="bc-article__btn-link btn btn-link" type="button">Загрузить еще</button>
      </div>
    </div>
  </div>
</div>

lib/bloomchain_web/templates/page/people.html.eex
<div class="container py-4">
  <div class="row">
    <div class="col-md-12 mt-md-0"><a class="bc-article__overlay-link" href="#">
        <div class="bc-article__image"><img src="assets/images/img-bitcoin.jpg">
          <p>Курс криптовалюты Ethereum превысил $400</p><span class="bc-article__image__published small">2 часа назад</span>
          <div class="d-flex align-items-center"><i class="mr-1 icon-user-white"></i><span class="small mr-sm-4 mr-3">Stanley Wade</span><i class="mr-1 icon-view-white"></i><span class="small mr-sm-4 mr-3">23</span><i class="mr-1 icon-clock-white"></i><span class="small">17 мин</span></div>
        </div></a>
      <div class="mt-4"></div><a class="bc-article__heading bc-article__heading__h2" href="http://">Криптобиржа Coincheck вернет средства своим клиентам после взлома</a>
      <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
      <hr class="bc-article__separator mx-0 my-3">
      <div class="row">
        <div class="col-xl-6"><a class="bc-article__heading" href="http://">Земан призвал Москву и Запад отказаться от санкций</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3"><a class="bc-article__heading" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3 d-xl-none">
        </div>
        <div class="col-xl-6"><a class="bc-article__heading" href="http://">Земан призвал Москву и Запад отказаться от санкций</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
          <hr class="bc-article__separator mx-0 my-3"><a class="bc-article__heading" href="http://">МГУ потратил 500 000 рублей на билеты на концерты Лепса, L'One и IOWA</a>
          <div class="d-flex align-items-center mt-3"><span class="small mr-4">2 часа назад</span><i class="mr-1 icon-view"></i><span class="small mr-4">10 235</span><i class="mr-1 icon-comment"></i><span class="small mr-4">2</span><i class="mr-1 icon-clock"></i><span class="small">17 мин</span></div>
        </div>
      </div>
    </div>
  </div>
</div>