lib/bloomchain_web/router.ex
defmodule BloomchainWeb.Router do
  use BloomchainWeb, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug :fetch_session
    plug(:fetch_flash)
    # plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :customer do
    plug(BloomchainWeb.Plug.Redirect)
    plug(BloomchainWeb.Plug.SetSectionData)
  end

  pipeline :admin do
    plug(BloomchainWeb.Plug.Authentication)
    plug(BloomchainWeb.Plug.EnsureAuthentication)
    plug(:put_layout, {BloomchainWeb.LayoutView, :admin})
  end

  pipeline :sign_in do
    plug(:put_layout, {BloomchainWeb.LayoutView, :sign_in})
  end

  pipeline :api do
    plug(:accepts, ["json", "multipart/form-data"])
  end

  pipeline :xml do
    plug(:accepts, ["xml"])
    plug(:put_layout, false)
  end

  scope "/admin", BloomchainWeb, as: :admin do
    pipe_through([:browser, :admin])

    get("/", Admin.HomeController, :index)

    scope "/api/v1" do
      pipe_through [:api]

      get("/articles/search", Admin.Api.V1.ArticleController, :search)
      resources("/articles", Admin.Api.V1.ArticleController)

      get "/users/current", Admin.Api.V1.UserController, :current
      resources("/users", Admin.Api.V1.UserController)

      resources("/tags", Admin.Api.V1.TagController)
      resources("/media", Admin.Api.V1.MediaController)
      resources("/subscribers", Admin.Api.V1.SubscriberController, only: [:index])
      resources("/archives", Admin.Api.V1.ArchiveController)
      resources("/authors", Admin.Api.V1.AuthorController)
      resources("/sections", Admin.Api.V1.SectionController)
      resources("/redirects", Admin.Api.V1.RedirectController)
      resources("/banners", Admin.Api.V1.BannerController)
      resources("/statistics", Admin.Api.V1.StatisticController, only: [:index])
    end

    scope "/preview" do
      pipe_through [:customer]

      get "/articles/:type/:slug", Admin.Preview.ArticleController, :show
    end

    get("/*path", Admin.HomeController, :index)
  end

  scope "/session", BloomchainWeb do
    pipe_through([:browser, :sign_in])

    delete("/", SessionController, :delete)
    resources("/", SessionController, only: [:create, :new])
  end

  get("/sitemap.xml", BloomchainWeb.SitemapController, :index)

  scope "/sitemap", BloomchainWeb do
    pipe_through([:xml])

    resources("/", SitemapController, only: [:show], param: "property")
  end

  scope "/api", BloomchainWeb do
    pipe_through [:api]

    resources("/index", Api.IndexController, only: [:index])
    resources("/subscription", Api.SubscriptionController, only: [:create])
    resources("/events", Api.EventController, only: [:create])
  end

  scope "/", BloomchainWeb do
    pipe_through([:xml])

    get("/feed", FeedController, :index)
    get("/:type/feed", FeedController, :show)
  end

  scope "/", BloomchainWeb do
    pipe_through([:browser, :customer])

    get("/", PageController, :index)

    get("/search", SearchController, :index)
    get("/tag/:slug", TagController, :show)

    get("/:type/:slug", ArticleController, :show)
    get("/:type", SectionController, :index)
  end
end

lib/bloomchain_web/views/layout_view.ex
defmodule BloomchainWeb.LayoutView do
  use BloomchainWeb, :view
  alias BloomchainWeb.Router.Helpers
  alias Bloomchain.Content.Banner
  alias BloomchainWeb.Uploaders.File

  def title(assigns) do
    assigns[:title] || get_in(assigns, [:article, :title]) ||
      get_in(assigns, [:sections, assigns.conn.path_params["type"], :seo, "title"]) ||
      get_in(assigns, [:sections, "default", :seo, "title"])
  end

  def meta(:description, assigns) do
    assigns[:description] || get_in(assigns, [:article, :seo_settings, "description"]) ||
      get_in(assigns, [:sections, assigns.conn.path_params["type"], :seo, "description"]) ||
      get_in(assigns, [:sections, "default", :seo, "description"])
  end

  def meta(:keywords, assigns) do
    (assigns[:keywords] || get_in(assigns, [:article, :seo_settings, "keywords"]) || [])
    |> Enum.join(", ")
  end

  def meta(:og_url, assigns) do
    assigns[:og_url] || get_in(assigns, [:article, :seo_settings, "og_url"]) || ""
  end

  def meta(:og_type, assigns) do
    assigns[:og_type] || get_in(assigns, [:article, :seo_settings, "og_type"]) || ""
  end

  def meta(:og_title, assigns) do
    assigns[:og_title] || assigns[:title] ||
      get_in(assigns, [:article, :seo_settings, "og_title"]) ||
      get_in(assigns, [:sections, assigns.conn.path_params["type"], :seo, "title"]) ||
      get_in(assigns, [:sections, "default", :seo, "title"])
  end

  def meta(:og_description, assigns) do
    assigns[:og_description] || assigns[:description] ||
      get_in(assigns, [:article, :seo_settings, "og_description"]) ||
      get_in(assigns, [:sections, assigns.conn.path_params["type"], :seo, "description"]) ||
      get_in(assigns, [:sections, "default", :seo, "description"])
  end

  def meta(:og_image, assigns) do
    assigns[:og_image] || get_in(assigns, [:article, :seo_settings, "og_image"]) ||
      Helpers.static_url(assigns.conn, "/customer/images/logo.jpg")
  end

  def meta(:twitter_title, assigns) do
    assigns[:twitter_title] || assigns[:title] ||
      get_in(assigns, [:article, :seo_settings, "twitter_title"]) ||
      get_in(assigns, [:sections, assigns.conn.path_params["type"], :seo, "title"]) ||
      get_in(assigns, [:sections, "default", :seo, "title"])
  end

  def meta(:twitter_description, assigns) do
    assigns[:twitter_description] || assigns[:description] ||
      get_in(assigns, [:article, :seo_settings, "twitter_description"]) ||
      get_in(assigns, [:sections, assigns.conn.path_params["type"], :seo, "description"]) ||
      get_in(assigns, [:sections, "default", :seo, "description"])
  end

  def meta(:twitter_image, assigns) do
    assigns[:twitter_image] || get_in(assigns, [:article, :seo_settings, "twitter_image"]) ||
      Helpers.static_url(assigns.conn, "/customer/images/logo.jpg")
  end

  def rss_link(conn) do
    type = conn.path_info |> List.first()

    if(Enum.member?(~w(newsfeed detailed in-russia people research analysis calendar), type)) do
      feed_path(conn, :show, type)
    else
      feed_path(conn, :index)
    end
  end

  def active_navlink_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])

    if Regex.match?(~r/#{path}/, current_path) do
      "nav-link nav-link--active"
    else
      "nav-link"
    end
  end
end

lib/bloomchain_web/templates/layout/_banner.html.eex
<%= if @banner do %>
  <div class="bc-advertising__image-hot mx-auto">
    <%=
      content_tag(:picture, class: "w-100") do
        [
          tag(:source, srcset: File.url({@banner.desktop_cover.file, @banner.desktop_cover}), media: "(min-width: 980px)"),
          img_tag(File.url({@banner.mobile_cover.file, @banner.mobile_cover}), class: "js-banner", data_banner_id: @banner.id, data_target_url: @banner.target_url)
        ]
      end
    %>
  </div>
<% end %>

lib/bloomchain_web/templates/layout/_footer.html.eex
<div class="bc-footer">
  <div class="container">
    <div class="pt-5 d-block">
      <h4 class="text-white mb-3 text-center d-flex justify-content-center">Только&nbsp;<b>DIGITAL</b>&nbsp;финансы</h4>
      <div class="row mb-5">
        <div class="col-sm-12 col-md-4 d-flex align-items-center justify-content-center justify-content-md-end">
          <i class="icon icon--check mr-2"></i>
          <p class="text-white mb-0 text-center d-flex justify-content-center">в одном письме</p>
        </div>
        <div class="col-sm-12 col-md-4 d-flex align-items-center justify-content-center">
          <i class="icon icon--check mr-2"></i>
          <p class="text-white mb-0 text-center d-flex justify-content-center">под рукой</p>
        </div>
        <div class="col-sm-12 col-md-4 d-flex align-items-center justify-content-center justify-content-md-start">
          <i class="icon icon--check mr-2"></i>
          <p class="text-white mb-0 text-center d-flex justify-content-center">2 раза в месяц</p>
        </div>
      </div>
    </div>
    <%= render "_subscribe_form.html", conn: @conn %>
  </div>
  <div class="container mt-4 mt-md-5">
    <div class="row">
      <div class="col">
        <nav class="bc-footer__nav">
          <%= for i <- ~w(newsfeed detailed analysis people in-russia calendar research-archive) do %>
            <%= link(@conn.assigns.sections[i].name, to: section_path(@conn, :index, i), class: "bc-footer__nav-link") %>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
  <div class="bc-footer__info container mt-4 pt-2 pb-5">
    <div class="row">
      <div class="bc-footer__logo col-xl-3 col-lg-3 col-md-3">
        <a href="/">
          <img
            class="bc-footer__img js-lazy"
            data-src='<%= static_path(@conn, "/customer/images/logo-white.svg") %>'
            src='<%= static_path(@conn, "/customer/images/footer_logo_placeholder.jpg") %>'
          >
        </a>
      </div>
      <div class="bc-footer__links col-xl-6 col-lg-5 col-md-6">
        <div class="row no-gutters flex-column flex-sm-row">
          <a class="bc-footer__link" target="_blank" href="https://bloomchain-cdn.s3.amazonaws.com/uploads/pdf/26161a6e-d0e7-11ea-b605-0242ac130003/original.pdf?v=63763169378">Реклама на сайте</a>
          <a class="bc-footer__link" target="_blank" href="mailto:contact@bloomchain.ru">contact@bloomchain.ru</a>
          <a class="bc-footer__link" target="_blank" href="tel:+79516564156">+7 (951) 656-41-56</a>
          <a class="bc-footer__link" target="_blank" href="<%= rss_link(@conn) %>">RSS</a>
        </div>
        <div class="mt-3">
          <div class="bc-footer__p">Все права защищены © ООО Ворк Майл, 2016-2020</div>
          <div class="bc-footer__p mt-2 mb-1">Любое использование материалов допускается только с согласия редакции. Новости, аналитика и другие материалы, представленные на сайте bloomchain.ru, не являются офертой или рекомендацией к покупке или продаже.</div>
          <p class="text-white mb-0" style="font-size: 11px">18&#43;</p>
          <button class="btn bg-transparent border-0 bc-footer__link bc-footer__link_small px-0" type="button" data-toggle="modal" data-target="#privacy-policy-dialog">Политика конфиденциальности</button>
        </div>
      </div>
      <div class="bc-footer__social col-xl-3 col-lg-4 col-md-3">
        <a class="icon-vk-round" href="https://vk.com/bloomchain" target="_blank"></a>
        <a class="icon-fb-round" href="https://www.facebook.com/BloomChainNews" target="_blank"></a>
        <a class="icon-tw-round" href="https://twitter.com/BloomChainNews" target="_blank"></a>
        <a class="icon-tg-round" href="tg://resolve?domain=bloomchain" target="_blank"></a>
      </div>
    </div>
  </div>
</div>

lib/bloomchain_web/templates/layout/_header.html.eex
<header class="bc-header navbar navbar-expand-md navbar-light">
  <div class="container py-2 py-md-4">
    <a href="/">
      <img class="bc-header__logo" src='<%= static_path(@conn, "/customer/images/logo.svg") %>'>
    </a>
    <div class="d-none d-md-block">
      <div class="bc-header__converter">
        <div class="bc-header__converter__currency align-items-center">
          <input class="bc-header__converter__input form-control js-currency-converter-input" type="number" min="0" max="100" step="0.1" value="1">
          <div class="input-group ml-1">
            <select class="select js-crypto-currency-select">
              <option value="BTC" selected>BTC</option>
              <option value="ETH">ETH</option>
              <option value="XRP">XRP</option>
              <option value="LTC">LTC</option>
              <option value="BCH">BCH</option>
            </select>
          </div>
        </div>
        <div class="bc-header__converter__equal ml-4 mr-2">=</div>
        <div class="bc-header__converter__currency align-items-center">
          <input type="text" readonly class="bc-header__converter__value js-currency-converter-output"></input>
          <div class="input-group ml-1">
            <select class="select js-finance-currency-select">
              <option value="USD" selected>USD</option>
              <option value="EUR">EUR</option>
              <option value="RUB">RUB</option>
              <option value="JPY">JPY</option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <div class="bc-header__social">
      <a class="icon-fb" href="https://www.facebook.com/BloomChainNews" target="_blank"></a>
      <a class="icon-vk ml-3" href="https://vk.com/bloomchain" target="_blank"></a>
      <a class="icon-tg ml-3" href="tg://resolve?domain=bloomchain" target="_blank"></a>
      <a class="icon-tw ml-3" href="https://twitter.com/BloomChainNews" target="_blank"></a>
    </div>
    <div class="d-inline-flex d-md-none js-search-container">
      <button type="button" class="bc-header__search__icon bc-header__search__icon_mobile btn-link nav-link px-0 js-open-search-button js-mobile-open-search-button">
        <i class="icon-search"></i>
      </button>

      <%= form_for @conn, search_path(@conn, :index), [method: :get, class: "bc-header__search__box bc-header__search__box_mobile d-none js-mobile-search-form"], fn f-> %>

        <%= submit class: "bc-header__search__icon btn-link nav-link pr-0 js-mobile-search-icon" do %>
          <i class="icon-search"></i>
        <% end %>

        <%= text_input f, :query, placeholder: "Поиск по сайту", aria_label: "Search", type: "search", class: "bc-header__search__input_mobile form-control" %>

        <button type="button" class="bc-header__search__close bc-header__search__close_mobile hamburger hamburger--slider-r is-active js-close-search-button js-mobile-open-search-button">
          <div class="hamburger-box">
            <div class="hamburger-inner"></div>
          </div>
        </button>

      <% end %>

      <button class="bc-article__z-index-100 navbar-toggler hamburger--slider-r px-0 ml-4 js-mobile-menu-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </button>
    </div>
  </div>
  <hr class="bc-header__separator m-0 d-none d-md-block" />
  <div class="container navbar-collapse collapse py-2" id="navbarSupportedContent">
    <nav class="navbar-nav bc-header__nav">
      <%= for i <- ~w(newsfeed detailed analysis people calendar research research-archive) do %>
        <div class="nav-item">
          <%= link(@conn.assigns.sections[i].name, to: section_path(@conn, :index, i), class: active_navlink_class(@conn, section_path(@conn, :index, i))) %>
        </div>
      <% end %>
    </nav>
    <ul class="navbar-nav d-none d-md-flex bc-header__search js-search-container">
      <li class="nav-item d-flex align-items-center w-100">
        <button type="button" class="bc-header__search__icon btn-link nav-link pr-0 js-open-search-button">
          <i class="icon-search"></i>
        </button>

        <%= form_for @conn, search_path(@conn, :index), [method: :get, class: "bc-header__search__box d-none js-search-form"], fn f-> %>

          <%= submit class: "bc-header__search__icon btn-link nav-link pr-0" do %>
            <i class="icon-search"></i>
          <% end %>

          <%= text_input f, :query, placeholder: "Поиск по сайту (по релевантности)", aria_label: "Search", type: "search", class: "bc-header__search__input form-control" %>

          <button type="button" class="bc-header__search__close hamburger hamburger--slider-r is-active js-close-search-button">
            <div class="hamburger-box">
              <div class="hamburger-inner"></div>
            </div>
          </button>

        <% end %>
      </li>
    </ul>
  </div>
</header>

lib/bloomchain_web/templates/layout/_privacy_police_dialog.html.eex
<div class="modal fade" id="privacy-policy-dialog" tabindex="-1" role="dialog" aria-labelledby="privacy policy" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-body my-4 px-sm-4">
        <div class="d-flex align-items-center">
          <h5 class="modal-title">Политика конфиденциальности</h5>
          <button class="hamburger hamburger--slider-r is-active close p-0 ml-auto" type="button" data-dismiss="modal" aria-label="Close">
            <div class="hamburger-box">
              <div class="hamburger-inner"></div>
            </div>
          </button>
        </div>
        <div class="bc-article__paragraph mt-4">
          <h2>Политика конфиденциальности</h2>
          <ul>
            <h4>1. ОБЩИЕ ПОЛОЖЕНИЯ</h4>
            <li>1.1. В рамках настоящей Политики конфиденциальности ООО «Ворк Майл» (далее – Политика) используются следующие понятия:</li>
            <li>1.1.1. Персональная информация — информация, которую Пользователь предоставляет о себе самостоятельно в процессе использования Сервисов, включая персональные данные Пользователя. Обязательная для предоставления Сервисов информация помечена специальным образом. Иная информация предоставляется Пользователем на его усмотрение;
            — данные, которые автоматически передаются сервисам Сайта в процессе их использования с помощью установленного на устройстве Пользователя программного обеспечения, в том числе IP-адрес, данные файлов cookie, информация о браузере Пользователя (или иной программе, с помощью которой осуществляется доступ к сервисам), технические характеристики оборудования и программного обеспечения, используемых Пользователем, дата и время доступа к сервисам, адреса запрашиваемых страниц и иная подобная информация.
            — иная информация о Пользователе, обработка которой предусмотрена Соглашением об использовании Сайта.</li>
            <li>1.1.2. Сайт – оператор персональных данных (оператор) в лице Общества с ограниченной ответственностью «Ворк Майл», на которое зарегистрирован сайт с доменным именем www.bloomchain.ru;</li>
            <li>1.1.3. Обработка персональных данных – любое действие (операция) или совокупность действий (операций) с персональными данными, совершаемых с использованием средств автоматизации или без их использования. Обработка персональных данных включает в себя, в том числе:
            <ul>
              <li>— сбор;</li>
              <li>— запись;</li>
              <li>— систематизацию;</li>
              <li>— накопление;</li>
              <li>— хранение;</li>
              <li>— уточнение (обновление, изменение);</li>
              <li>— извлечение;</li>
              <li>— использование;</li>
              <li>— передачу (распространение, предоставление, доступ);</li>
              <li>— обезличивание;</li>
              <li>— блокирование;</li>
              <li>— удаление;</li>
              <li>— уничтожение.</li>
            </ul>
            </li>
            <li>1.1.4. Пользователь – субъект персональных данных.</li>
            <li>1.2. Настоящая Политика применяется только к Сайту www.bloomchain.ru. Сайт www.bloomchain.ru не контролирует и не несет ответственности за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на Сайте www.bloomchain.ru.</li>
            <li>1.3. Настоящая Политика действует в отношении всей информации, размещенной на сайте в сети Интернет по адресу: www.bloomchain.ru (далее — Сайт).</li>
            <li>1.4. Использование сервисов Сайта означает безоговорочное согласие Пользователя с настоящей Политикой и указанными в ней условиями обработки его персональной информации; в случае несогласия с этими условиями Пользователь должен воздержаться от использования сервисов.</li>
            <h4>2. ЦЕЛИ ОБРАБОТКИ ПЕРСОНАЛЬНОЙ ИНФОРМАЦИИ ПОЛЬЗОВАТЕЛЕЙ</h4>
            <li>2.1. Сайт обрабатывает только ту персональную информацию, которая необходима для предоставления сервисов или исполнения соглашений и договоров с Пользователем, за исключением случаев, когда законодательством предусмотрена обязательная обработка персональной информации в течение определенного законом срока.</li>
            <li>2.2. Персональную информацию Пользователя Сайт обрабатывает в следующих целях:</li>
            <li>2.2.1. Идентификации Пользователя, зарегистрированного на Сайте.</li>
            <li>2.2.2. Предоставления Пользователю доступа к персонализированным ресурсам Сайта.</li>
            <li>2.2.3. Установления с Пользователем обратной связи, включая направление уведомлений, запросов, касающихся использования Сайта, оказания услуг, обработку запросов и заявок от Пользователя.</li>
            <li>2.2.4. Определения места нахождения Пользователя для обеспечения безопасности, предотвращения мошенничества.</li>
            <li>2.2.5. Подтверждения достоверности и полноты персональных данных, предоставленных Пользователем.</li>
            <li>2.2.6. Создания учетной записи для размещения информации на Сайте и использования возможности комментирования, если Пользователь дал согласие на создание учетной записи.</li>
            <li>2.2.7. Уведомления Пользователя Сайта о допущенных нарушениях в использовании Сайта.</li>
            <li>2.2.8. Предоставления Пользователю эффективной клиентской и технической поддержки при возникновении проблем, связанных с использованием Сайта.</li>
            <li>2.2.9. Осуществления рекламной деятельности с согласия Пользователя.</li>
            <h4>3. УСЛОВИЯ ОБРАБОТКИ ПЕРСОНАЛЬНОЙ ИНФОРМАЦИИ ПОЛЬЗОВАТЕЛЕЙ И ЕЁ ПЕРЕДАЧИ ТРЕТЬИМ ЛИЦАМ</h4>
            <li>3.1. Сайт обрабатывает персональную информацию Пользователей в соответствии с внутренними регламентами конкретных сервисов.</li>
            <li>3.2. В отношении персональной информации Пользователя сохраняется ее конфиденциальность, кроме случаев добровольного предоставления Пользователем информации о себе для общего доступа неограниченному кругу лиц. При использовании отдельных сервисов Пользователь соглашается с тем, что определенная часть его персональной информации становится общедоступной.</li>
            <li>3.3. Сайт вправе передать персональную информацию Пользователя третьим лицам в следующих случаях:</li>
            <li>3.3.1. Пользователь выразил согласие на такие действия.</li>
            <li>3.3.2. Передача необходима для использования Пользователем определенного сервиса либо для исполнения определенного соглашения или договора с Пользователем.</li>
            <li>3.3.4. Передача предусмотрена российским или иным применимым законодательством в рамках установленной законодательством процедуры.</li>
            <li>3.3.5. В случае продажи Сайта к приобретателю переходят все обязательства по соблюдению условий настоящей Политики применительно к полученной им персональной информации.</li>
            <li>3.4. Обработка персональных данных Пользователя осуществляется без ограничения срока любым законным способом, в том числе в информационных системах персональных данных с использованием средств автоматизации или без использования таких средств. Обработка персональных данных Пользователей осуществляется в соответствии с Федеральным законом от 27.07.2006 N 149-ФЗ «Об информации, информационных технологиях и о защите информации» и иными нормативно-правовыми актами РФ, а также локальными нормативными актами оператора персональных данных.</li>
            <li>3.5. Администрация Сайта принимает необходимые организационные и технические меры для защиты персональной информации Пользователя от неправомерного или случайного доступа, уничтожения, изменения, блокирования, копирования, распространения, а также от иных неправомерных действий третьих лиц.</li>
            <li>3.6. Администрация Сайта совместно с Пользователем принимает все необходимые меры по предотвращению убытков или иных отрицательных последствий, вызванных утратой или разглашением персональных данных Пользователя.</li>
            <h4>4. ОБЯЗАТЕЛЬСТВА СТОРОН</h4>
            <li>4.1. Пользователь обязан:</li>
            <li>4.1.1. Предоставить информацию о персональных данных, необходимую для пользования Сайтом.</li>
            <li>4.1.2. Обновлять, дополнять предоставленную информацию о персональных данных в случае изменения данной информации.</li>
            <li>4.1.3. Нести ответственность за предоставление данных иного лица.</li>
            <li>4.2. Администрация Сайта обязана:</li>
            <li>4.2.1. Использовать полученную информацию исключительно для целей, указанных в настоящей Политике.</li>
            <li>4.2.2. Обеспечить обработку конфиденциальной информации в тайне, не разглашать без предварительного письменного разрешения Пользователя, а также не осуществлять продажу, обмен, опубликование либо разглашение иными возможными способами переданных персональных данных Пользователя, за исключением предусмотренных настоящей Политикой случаев.</li>
            <li>4.2.3. Принимать меры предосторожности для защиты конфиденциальности персональных данных Пользователя согласно порядку, обычно используемому для защиты такого рода информации в существующем деловом обороте.</li>
            <li>4.2.4. Осуществить блокирование персональных данных, относящихся к соответствующему Пользователю, с момента обращения или запроса Пользователя или его законного представителя либо уполномоченного органа по защите прав субъектов персональных данных на период проверки в случае выявления недостоверных персональных данных или неправомерных действий.</li>
            <h4>5. ОТВЕТСТВЕННОСТЬ СТОРОН</h4>
            <li>5.1. В случае утраты или разглашения конфиденциальной информации Администрация Сайта не несет ответственности, если данная конфиденциальная информация:</li>
            <li>5.1.1. Стала публичным достоянием до ее утраты или разглашения.</li>
            <li>5.1.2. Была получена от третьей стороны до момента ее получения Администрацией Сайта.</li>
            <li>5.1.3. Была разглашена с согласия Пользователя.</li>
            <h4>6. ДОПОЛНИТЕЛЬНЫЕ УСЛОВИЯ</h4>
            <li>6.1. Настоящая Политика вступает в силу с момента публикации на Сайте.</li>
            <li>6.2. Администрация Сайта вправе вносить изменения в настоящую Политику без согласия Пользователя. Использование Сервисов после внесения любых поправок в Политику означает принятие данных изменений.</li>
            <li>6.3. Новая политика конфиденциальности вступает в силу с момента ее размещения на Сайте, если иное не предусмотрено новой редакцией Политики конфиденциальности.</li>
            <li>6.4. Все предложения или вопросы по настоящей Политике следует сообщать по адресу электронной почты: <a href="mailto:contact@bloomchain.ru">contact@bloomchain.ru.</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

lib/bloomchain_web/templates/layout/_subscribe_form.html.eex
<form class="js-form-subscription">
  <div class="bc-footer__subscribe align-items-center align-items-md-start">
    <div id="js-subscription-input" class="bc-footer__input_wrapper">
        <input name="email" type="email" required placeholder="Ваш Email" class="bc-footer__input bg-transparent border-0">
        <p class="form__helper-text js-subscription-error-msg"></p>
    </div>
    <button type="submit" class="bc-footer__button btn btn-primary ml-md-5">Подписаться</button>
  </div>
  <p class="bc-footer__p text-center mt-3">*Нажимая подписаться вы соглашаетесь с политикой конфиденциальности</p>
</form>